### ISSUE TITLE
error when inputing player name

### ISSUE THREAD

**Issue by vincent-lafouasse** [JRConti/TapnSwap-RL#2]
```
---------------------------------------
               TAP 'N SWAP
---------------------------------------


Name of player ?
JR
Traceback (most recent call last):
  File "main.py", line 244, in <module>
    game_mngr()
  File "main.py", line 221, in game_mngr
    player = input_names(n_players = 1)
  File "main.py", line 112, in input_names
    player = input('Name of player ? \n')
  File "<string>", line 1, in <module>
NameError: name 'JR' is not defined
```

**Comment by vincent-lafouasse** [comment]
I am running on `zsh` on macOS High Sierra 10.13.1

**Comment by JRConti** [comment]
According to [https://stackoverflow.com/questions/42304421/python-input-issues-with-mac](url), the reason might be that you're using Python2. You should upgrade Python to Python3 by entering `brew install python3` in command line if you use homebrew, or via pip otherwise.

**Comment by vincent-lafouasse** [comment]
Thank you, this has been solved by upgrading to python3
